# Generated by Django 4.2.7 on 2023-12-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='std1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.PositiveIntegerField()),
                ('course', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=25)),
            ],
        ),
    ]
